2022-01-12 11:10:40,049	INFO head.py:128 -- Dashboard head grpc address: 0.0.0.0:33555
2022-01-12 11:10:40,049	INFO dashboard.py:92 -- Setup static dir for dashboard: /home/reza/anaconda3/lib/python3.8/site-packages/ray/dashboard/client/build
2022-01-12 11:10:40,050	INFO head.py:55 -- Connect to GCS at 131.215.21.210:34345
2022-01-12 11:10:40,053	INFO utils.py:200 -- Get all modules by type: DashboardHeadModule
2022-01-12 11:10:40,278	WARNING tune_head.py:22 -- tune module is not available: cannot import name 'Analysis' from 'ray.tune' (/home/reza/anaconda3/lib/python3.8/site-packages/ray/tune/__init__.py)
2022-01-12 11:10:40,278	INFO head.py:168 -- Loading DashboardHeadModule: <class 'ray.dashboard.modules.actor.actor_head.ActorHead'>
2022-01-12 11:10:40,278	INFO head.py:168 -- Loading DashboardHeadModule: <class 'ray.dashboard.modules.event.event_head.EventHead'>
2022-01-12 11:10:40,279	INFO head.py:168 -- Loading DashboardHeadModule: <class 'ray.dashboard.modules.job.job_head.JobHead'>
2022-01-12 11:10:40,279	INFO head.py:168 -- Loading DashboardHeadModule: <class 'ray.dashboard.modules.log.log_head.LogHead'>
2022-01-12 11:10:40,279	INFO head.py:168 -- Loading DashboardHeadModule: <class 'ray.dashboard.modules.node.node_head.NodeHead'>
2022-01-12 11:10:40,279	INFO head.py:168 -- Loading DashboardHeadModule: <class 'ray.dashboard.modules.reporter.reporter_head.ReportHead'>
2022-01-12 11:10:40,279	INFO head.py:168 -- Loading DashboardHeadModule: <class 'ray.dashboard.modules.snapshot.snapshot_head.APIHead'>
2022-01-12 11:10:40,279	INFO head.py:168 -- Loading DashboardHeadModule: <class 'ray.dashboard.modules.tune.tune_head.TuneController'>
2022-01-12 11:10:40,279	INFO head.py:173 -- Loaded 8 modules.
2022-01-12 11:10:40,282	INFO head.py:253 -- Dashboard head http address: 127.0.0.1:8265
2022-01-12 11:10:40,283	INFO head.py:271 -- <ResourceRoute [GET] <PlainResource  /> -> <function Dashboard.get_index at 0x7fa5e1bafdc0>
2022-01-12 11:10:40,283	INFO head.py:271 -- <ResourceRoute [GET] <PlainResource  /favicon.ico> -> <function Dashboard.get_favicon at 0x7fa5e1bafee0>
2022-01-12 11:10:40,283	INFO head.py:271 -- <ResourceRoute [GET] <StaticResource  /static -> PosixPath('/home/reza/anaconda3/lib/python3.8/site-packages/ray/dashboard/client/build/static')> -> <bound method StaticResource._handle of <StaticResource  /static -> PosixPath('/home/reza/anaconda3/lib/python3.8/site-packages/ray/dashboard/client/build/static')>>
2022-01-12 11:10:40,283	INFO head.py:271 -- <ResourceRoute [GET] <PlainResource  /logical/actor_groups> -> <function ActorHead.get_actor_groups at 0x7fa5e02ba8b0>
2022-01-12 11:10:40,284	INFO head.py:271 -- <ResourceRoute [GET] <PlainResource  /logical/actors> -> <function ActorHead.get_all_actors[cache ttl=2, max_size=128] at 0x7fa5e02ba9d0>
2022-01-12 11:10:40,284	INFO head.py:271 -- <ResourceRoute [GET] <PlainResource  /logical/kill_actor> -> <function ActorHead.kill_actor at 0x7fa5e02bab80>
2022-01-12 11:10:40,284	INFO head.py:271 -- <ResourceRoute [GET] <PlainResource  /events> -> <function EventHead.get_event[cache ttl=2, max_size=128] at 0x7fa5e02c4280>
2022-01-12 11:10:40,284	INFO head.py:271 -- <ResourceRoute [GET] <PlainResource  /api/version> -> <function JobHead.get_version at 0x7fa5e00f6c10>
2022-01-12 11:10:40,284	INFO head.py:271 -- <ResourceRoute [GET] <DynamicResource  /api/packages/{protocol}/{package_name}> -> <function JobHead.get_package at 0x7fa5e00f6dc0>
2022-01-12 11:10:40,284	INFO head.py:271 -- <ResourceRoute [PUT] <DynamicResource  /api/packages/{protocol}/{package_name}> -> <function JobHead.upload_package at 0x7fa5e00f6f70>
2022-01-12 11:10:40,284	INFO head.py:271 -- <ResourceRoute [POST] <PlainResource  /api/jobs/> -> <function JobHead.submit_job at 0x7fa5e0101160>
2022-01-12 11:10:40,284	INFO head.py:271 -- <ResourceRoute [POST] <DynamicResource  /api/jobs/{job_id}/stop> -> <function JobHead.stop_job at 0x7fa5e0101310>
2022-01-12 11:10:40,284	INFO head.py:271 -- <ResourceRoute [GET] <DynamicResource  /api/jobs/{job_id}> -> <function JobHead.get_job_status at 0x7fa5e01014c0>
2022-01-12 11:10:40,284	INFO head.py:271 -- <ResourceRoute [GET] <DynamicResource  /api/jobs/{job_id}/logs> -> <function JobHead.get_job_logs at 0x7fa5e0101670>
2022-01-12 11:10:40,284	INFO head.py:271 -- <ResourceRoute [GET] <PlainResource  /log_index> -> <function LogHead.get_log_index at 0x7fa5e01050d0>
2022-01-12 11:10:40,284	INFO head.py:271 -- <ResourceRoute [GET] <PlainResource  /log_proxy> -> <function LogHead.get_log_from_proxy at 0x7fa5e01051f0>
2022-01-12 11:10:40,284	INFO head.py:271 -- <ResourceRoute [GET] <PlainResource  /nodes> -> <function NodeHead.get_all_nodes[cache ttl=2, max_size=128] at 0x7fa5e0105c10>
2022-01-12 11:10:40,284	INFO head.py:271 -- <ResourceRoute [GET] <DynamicResource  /nodes/{node_id}> -> <function NodeHead.get_node[cache ttl=2, max_size=128] at 0x7fa5e0105dc0>
2022-01-12 11:10:40,284	INFO head.py:271 -- <ResourceRoute [GET] <PlainResource  /memory/memory_table> -> <function NodeHead.get_memory_table at 0x7fa5e0105f70>
2022-01-12 11:10:40,284	INFO head.py:271 -- <ResourceRoute [GET] <PlainResource  /memory/set_fetch> -> <function NodeHead.set_fetch_memory_info at 0x7fa5e010d0d0>
2022-01-12 11:10:40,284	INFO head.py:271 -- <ResourceRoute [GET] <PlainResource  /node_logs> -> <function NodeHead.get_logs at 0x7fa5e010d1f0>
2022-01-12 11:10:40,284	INFO head.py:271 -- <ResourceRoute [GET] <PlainResource  /node_errors> -> <function NodeHead.get_errors at 0x7fa5e010d310>
2022-01-12 11:10:40,284	INFO head.py:271 -- <ResourceRoute [GET] <PlainResource  /api/launch_profiling> -> <function ReportHead.launch_profiling at 0x7fa5c1f7c670>
2022-01-12 11:10:40,284	INFO head.py:271 -- <ResourceRoute [GET] <PlainResource  /api/ray_config> -> <function ReportHead.get_ray_config at 0x7fa5c1f7c790>
2022-01-12 11:10:40,285	INFO head.py:271 -- <ResourceRoute [GET] <PlainResource  /api/cluster_status> -> <function ReportHead.get_cluster_status at 0x7fa5c1f7c8b0>
2022-01-12 11:10:40,285	INFO head.py:271 -- <ResourceRoute [GET] <PlainResource  /api/actors/kill> -> <function APIHead.kill_actor_gcs at 0x7fa5c1f85e50>
2022-01-12 11:10:40,285	INFO head.py:271 -- <ResourceRoute [GET] <PlainResource  /api/snapshot> -> <function APIHead.snapshot at 0x7fa5c1f85f70>
2022-01-12 11:10:40,285	INFO head.py:271 -- <ResourceRoute [GET] <PlainResource  /tune/info> -> <function TuneController.tune_info at 0x7fa5a6b389d0>
2022-01-12 11:10:40,285	INFO head.py:271 -- <ResourceRoute [GET] <PlainResource  /tune/availability> -> <function TuneController.get_availability at 0x7fa5a6b38af0>
2022-01-12 11:10:40,285	INFO head.py:271 -- <ResourceRoute [GET] <PlainResource  /tune/set_experiment> -> <function TuneController.set_tune_experiment at 0x7fa5a6b38c10>
2022-01-12 11:10:40,285	INFO head.py:271 -- <ResourceRoute [GET] <PlainResource  /tune/enable_tensorboard> -> <function TuneController.enable_tensorboard at 0x7fa5a6b38d30>
2022-01-12 11:10:40,285	INFO head.py:271 -- <ResourceRoute [GET] <StaticResource  /logs -> PosixPath('/home/reza/Dropbox/Prog/MERA/temp/session_2022-01-12_11-10-38_169951_152815/logs')> -> <bound method StaticResource._handle of <StaticResource  /logs -> PosixPath('/home/reza/Dropbox/Prog/MERA/temp/session_2022-01-12_11-10-38_169951_152815/logs')>>
2022-01-12 11:10:40,285	INFO head.py:272 -- Registered 32 routes.
2022-01-12 11:10:40,286	INFO datacenter.py:69 -- Purge data.
2022-01-12 11:10:40,286	INFO event_utils.py:123 -- Monitor events logs modified after 1642012840.059988 on /home/reza/Dropbox/Prog/MERA/temp/session_2022-01-12_11-10-38_169951_152815/logs/events, the source types are ['GCS'].
2022-01-12 11:10:40,289	INFO reporter_head.py:138 -- Subscribed to RAY_REPORTER:*
2022-01-12 11:10:40,289	INFO actor_head.py:71 -- Subscribed to ACTOR:*
2022-01-12 11:10:40,289	INFO actor_head.py:81 -- Getting all actor info from GCS.
2022-01-12 11:10:40,289	INFO node_head.py:249 -- Subscribed to <_Sender name:b'RAY_LOG_CHANNEL', is_pattern:False, receiver:<Receiver is_active:True, senders:1, qsize:0>>
2022-01-12 11:10:40,289	INFO node_head.py:309 -- Subscribed to b'ERROR_INFO:*'
2022-01-12 11:10:40,289	INFO actor_head.py:107 -- Received 0 actor info from GCS.
2022-01-12 11:10:40,606	INFO node_head.py:270 -- Received a log for 131.215.21.210 and autoscaler
2022-01-12 11:10:44,831	INFO node_head.py:270 -- Received a log for 131.215.21.210 and autoscaler
2022-01-12 11:10:49,761	INFO node_head.py:270 -- Received a log for 131.215.21.210 and autoscaler
2022-01-12 11:10:54,798	INFO node_head.py:270 -- Received a log for 131.215.21.210 and autoscaler
2022-01-12 11:10:59,839	INFO node_head.py:270 -- Received a log for 131.215.21.210 and autoscaler
2022-01-12 11:11:04,775	INFO node_head.py:270 -- Received a log for 131.215.21.210 and autoscaler
2022-01-12 11:11:09,818	INFO node_head.py:270 -- Received a log for 131.215.21.210 and autoscaler
2022-01-12 11:11:14,856	INFO node_head.py:270 -- Received a log for 131.215.21.210 and autoscaler
2022-01-12 11:11:19,795	INFO node_head.py:270 -- Received a log for 131.215.21.210 and autoscaler
2022-01-12 11:11:24,836	INFO node_head.py:270 -- Received a log for 131.215.21.210 and autoscaler
2022-01-12 11:11:29,876	INFO node_head.py:270 -- Received a log for 131.215.21.210 and autoscaler
2022-01-12 11:11:34,825	INFO node_head.py:270 -- Received a log for 131.215.21.210 and autoscaler
2022-01-12 11:11:39,864	INFO node_head.py:270 -- Received a log for 131.215.21.210 and autoscaler
2022-01-12 11:11:44,903	INFO node_head.py:270 -- Received a log for 131.215.21.210 and autoscaler
2022-01-12 11:11:49,842	INFO node_head.py:270 -- Received a log for 131.215.21.210 and autoscaler
2022-01-12 11:11:54,883	INFO node_head.py:270 -- Received a log for 131.215.21.210 and autoscaler
2022-01-12 11:11:59,613	ERROR node_head.py:241 -- Error updating node stats of cb7257dbae2c754564b6bece96d39bab19e712e07801f0bedb5a6163.
Traceback (most recent call last):
  File "/home/reza/anaconda3/lib/python3.8/site-packages/ray/dashboard/modules/node/node_head.py", line 234, in _update_node_stats
    reply = await stub.GetNodeStats(
  File "/home/reza/.local/lib/python3.8/site-packages/grpc/aio/_call.py", line 285, in __await__
    raise _create_rpc_error(self._cython_call._initial_metadata,
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1642014719.613740240","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":4133,"referenced_errors":[{"created":"@1642014719.613738060","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":397,"grpc_status":14}]}"
>
2022-01-12 11:12:00,322	ERROR node_head.py:133 -- Error updating nodes.
Traceback (most recent call last):
  File "/home/reza/anaconda3/lib/python3.8/site-packages/ray/dashboard/modules/node/node_head.py", line 99, in _update_nodes
    nodes = await self._get_nodes()
  File "/home/reza/anaconda3/lib/python3.8/site-packages/ray/dashboard/modules/node/node_head.py", line 83, in _get_nodes
    reply = await self._gcs_node_info_stub.GetAllNodeInfo(
  File "/home/reza/.local/lib/python3.8/site-packages/grpc/aio/_call.py", line 285, in __await__
    raise _create_rpc_error(self._cython_call._initial_metadata,
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1642014720.322142632","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":4133,"referenced_errors":[{"created":"@1642014720.322140493","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":397,"grpc_status":14}]}"
>
2022-01-12 11:12:00,322	ERROR head.py:90 -- Got RpcError when checking GCS is alive
Traceback (most recent call last):
  File "/home/reza/anaconda3/lib/python3.8/site-packages/ray/dashboard/head.py", line 83, in _check_once_synchrounously
    reply = self.gcs_heartbeat_info_stub.CheckAlive(
  File "/home/reza/.local/lib/python3.8/site-packages/grpc/_channel.py", line 826, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/reza/.local/lib/python3.8/site-packages/grpc/_channel.py", line 729, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1642014720.322508555","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":4133,"referenced_errors":[{"created":"@1642014720.322506643","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":397,"grpc_status":14}]}"
>
2022-01-12 11:12:00,615	ERROR node_head.py:241 -- Error updating node stats of cb7257dbae2c754564b6bece96d39bab19e712e07801f0bedb5a6163.
Traceback (most recent call last):
  File "/home/reza/anaconda3/lib/python3.8/site-packages/ray/dashboard/modules/node/node_head.py", line 234, in _update_node_stats
    reply = await stub.GetNodeStats(
  File "/home/reza/.local/lib/python3.8/site-packages/grpc/aio/_call.py", line 285, in __await__
    raise _create_rpc_error(self._cython_call._initial_metadata,
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1642014720.615800875","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":4133,"referenced_errors":[{"created":"@1642014720.615797592","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":397,"grpc_status":14}]}"
>
